// src/components/PhoneticForm.vue
<script setup lang="ts">
import FormInput from '@/components/form/FormInput.vue';
import FormButton from '@/components/form/FormButton.vue';
import { ref } from 'vue';
import PhoneticAlphabetChars from '@/enums/PhoneticAlphabetChars.ts';

const text = ref('')
const phonetics = ref<string[]>([])

function handleSubmit(): void {
  phonetics.value = text.value
    .trim()
    .split('')
    .map(
      (char) =>
        PhoneticAlphabetChars[char.toLowerCase() as keyof typeof PhoneticAlphabetChars] || char,
    )
}

function handleReset(): void {
  text.value = ''
  phonetics.value = []
}
</script>

<template>
  <form @submit.prevent="handleSubmit">
    <form-input id="text" type="text" label="Text" v-model="text" autofocus required />

    <div class="space-x-4">
      <form-button color="black" type="submit" @click="handleSubmit">Submit</form-button>

      <form-button plain type="button" @click="handleReset">Reset</form-button>
    </div>

    <div class="pt-4 prose">
      <ol v-if="phonetics.length > 0">
        <li v-for="(phonetic, index) in phonetics" :key="`${index}-${phonetic}`">
          {{ phonetic }}
        </li>
      </ol>
    </div>
  </form>
</template>

// src/Components/PhoneticForm.tsx
import { useState } from 'react'
import Input from './Form/Input.tsx'
import Button from './Form/Button.tsx'
import PhoneticAlphabet from '../Enums/PhoneticAlphabet.ts'

export default function PhoneticForm() {
  const [text, setText] = useState('')
  const [phonetics, setPhonetics] = useState<string[]>([])

  const handleSubmit = (event?: React.FormEvent<HTMLFormElement>) => {
    event?.preventDefault()

    setPhonetics(() =>
      text
        .trim()
        .split('')
        .map(
          (char) =>
            PhoneticAlphabet[char.toLowerCase() as keyof typeof PhoneticAlphabet] || char,
        ),
    )
  }

  const handleReset = () => {
    setText('');
    setPhonetics([]);
  };

  return (
    <div>
      <form onSubmit={handleSubmit}>
        <Input
          id="text"
          type="text"
          label="Text"
          value={text}
          onChange={(event) => setText(event.target.value)}
          autofocus
          required
        />

        <div className="space-x-4">
          <Button type="button" color="black" onClick={() => handleSubmit()}>
            Submit
          </Button>

          <Button type="button" plain onClick={handleReset}>
            Reset
          </Button>
        </div>
      </form>

      {phonetics.length > 0 && (
        <div className="pt-4 prose">
          <ol>
            {phonetics.map((phonetic, index) => (
              <li key={`${index}-${phonetic}`}>{phonetic}</li>
            ))}
          </ol>
        </div>
      )}
    </div>
  )
}
